pre-release-hook = [
    "git",
    "cliff",
    "-o",
    "CHANGELOG.md",
    "--tag",
    "{{version}}",
]

pre-release-replacements = [
    { file = "README.md", search = "rev: .*", replace = "rev: {{version}}" },
]

pre-release-commit-message = "chore: release {{version}}"
